<<<<<<< HEAD
apiVersion: v1
kind: ConfigMap
metadata:
  name: tim-configmap
data:
  key1: This is Timothy Tolulope's first key in config map
  key2:
    This is
    a multiple line
    key

=======
apiVersion: v1
kind: ConfigMap
metadata:
  name: tim-configmap
data:
  key1: This is Timothy Tolulope's first key in config map
  key2:
    This is
    a multiple line
    key

>>>>>>> db9df3f (Added new yaml files)
#kubectl describe configmap tim-configmap